name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  DOCKER_REPO: ${{ secrets.docker_repo }}
  PUBLICPASSWORD: ${{ secrets.docker_repo }}

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: | 
          chmod 777 -R scripts
  #        cd ./scripts && ./runbuilds.sh

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Push image
        run: |
          echo $DOCKER_REPO
          docker login -u=$DOCKER_REPO -p=$PUBLICPASSWORD
          chmod 777 -R scripts
   #       cd ./scripts && ./rundeploy.sh
